### ISSUE TITLE
Migrate to Prometheus Community?

### ISSUE THREAD

**Issue by SuperQ** [prometheus-community/prometheus-json-exporter#24]
Is there any interest in maintaining this exporter? Maybe we could move it to the Prometheus Community repos?

https://github.com/prometheus-community

**Comment by kawamuray** [comment]
Hi @SuperQ thanks for your interest.

I'm not sure sure how much that organization is open to accept repos that has not been well maintained by someone, so I think we need an active maintainer for this project anyway.
Let me try to do some cleanup for this project within a week first. In any case are you interested in helping to maintain this project?

**Comment by SuperQ** [comment]
Yes, as one of the Prometheus maintainers, I would be willing to sponsor getting maintenance started.

One of the things I was looking at was your prometheus-exporter-harness code. I think that something like that would be really useful for https://github.com/prometheus/common.

**Comment by kawamuray** [comment]
> Yes, as one of the Prometheus maintainers, I would be willing to sponsor getting maintenance started.

oh that's nice :) Let me prepare to transfer the ownership.

> One of the things I was looking at was your prometheus-exporter-harness code. I think that something like that would be really useful for https://github.com/prometheus/common.

Oh it's interesting to hear heat. I thought most exporter authors are just relying on standard prom modules because its just enough. 

so when it's ready I'll just ping you and move the ownership, does it works?

**Comment by SuperQ** [comment]
I filed an issue in the community tracker for this.

There are two ways to do the move.
* I can grant you an admin role to move the exporter. You can continue to be a contributor to the exporter.
* You can grant me admin access to this project and I can do the move for you.

Either way, you're welcome to continue to be a maintainer/contributor of the project after the move.

**Comment by kawamuray** [comment]
@SuperQ ok that works. Let me add you as an admin.
Before that one quick question; what's the difference between github.com/prometheus-community and github.com/prometheus ? Apparently both contains various repositories of exporter implementations.

**Comment by SuperQ** [comment]
FYI, It turns out it's not possible to make others "admin" on "personal" repos. I will create a group on prometheus-community so it can be moved.

* github.com/prometheus is for "official" projects maintained by the core team.
* github.com/prometheus-community is where we're putting community maintained projects. If a community project is popular enough, and there are enough core team members available, we may build a process to graduate them to the "official" org.

**Comment by kawamuray** [comment]
@SuperQ I see, thanks for the clarification!

>  I will create a group on prometheus-community so it can be moved.

I assume it's not ready yet? I've just tried to transfer the ownership but failed by lack of permission on prometheus-community.

**Comment by SuperQ** [comment]
I sent an invite to join the `json_exporter` team, but it looks like it expired a couple days ago. Once you accept the invite, you can transfer the project.

**Comment by kawamuray** [comment]
@SuperQ Ugh, sorry it seems that I overlooked the previous invitation.
I've just transferred the ownership and now this repo is at prometheus-community. 
Thanks for your help :)
